use crate::applicant::Applicant;

pub fn get_applicants() -> Vec<Applicant> {
    vec![
        Applicant {
            id: 1,
            last_name: "Бондаренко".into(),
            first_name: "Олена".into(),
            patronymic: "Іванівна".into(),
            address: "м. Київ, вул. Хрещатик, 10".into(),
            phone: "+380501112233".into(),
            grades: vec![10, 11, 9, 12],
        },
        Applicant {
            id: 2,
            last_name: "Шевченко".into(),
            first_name: "Тарас".into(),
            patronymic: "Григорович".into(),
            address: "м. Львів, вул. Франка, 5".into(),
            phone: "+380671234567".into(),
            grades: vec![3, 5, 4, 6],
        },
        Applicant {
            id: 3,
            last_name: "Мельник".into(),
            first_name: "Ірина".into(),
            patronymic: "Олексіївна".into(),
            address: "м. Одеса, вул. Дерибасівська, 22".into(),
            phone: "+380931112244".into(),
            grades: vec![6, 7, 5, 8],
        },
        Applicant {
            id: 4,
            last_name: "Ткаченко".into(),
            first_name: "Андрій".into(),
            patronymic: "Петрович".into(),
            address: "м. Харків, вул. Сумська, 15".into(),
            phone: "+380661234455".into(),
            grades: vec![2, 3, 4, 5],
        },
        Applicant {
            id: 5,
            last_name: "Коваль".into(),
            first_name: "Марія".into(),
            patronymic: "Сергіївна".into(),
            address: "м. Дніпро, пр. Яворницького, 30".into(),
            phone: "+380501239988".into(),
            grades: vec![12, 12, 11, 12],
        },
        Applicant {
            id: 6,
            last_name: "Кравець".into(),
            first_name: "Віктор".into(),
            patronymic: "Миколайович".into(),
            address: "м. Запоріжжя, вул. Соборна, 8".into(),
            phone: "+380671239900".into(),
            grades: vec![7, 6, 7, 6],
        },
        Applicant {
            id: 7,
            last_name: "Романюк".into(),
            first_name: "Софія".into(),
            patronymic: "Богданівна".into(),
            address: "м. Івано-Франківськ, вул. Незалежності, 3".into(),
            phone: "+380931238877".into(),
            grades: vec![9, 10, 8, 9],
        },
        Applicant {
            id: 8,
            last_name: "Гончар".into(),
            first_name: "Олег".into(),
            patronymic: "Васильович".into(),
            address: "м. Полтава, вул. Соборності, 12".into(),
            phone: "+380661237766".into(),
            grades: vec![4, 3, 5, 4],
        },
        Applicant {
            id: 9,
            last_name: "Лисенко".into(),
            first_name: "Наталія".into(),
            patronymic: "Ігорівна".into(),
            address: "м. Чернігів, вул. Шевченка, 7".into(),
            phone: "+380501236655".into(),
            grades: vec![8, 7, 9, 7],
        },
        Applicant {
            id: 10,
            last_name: "Захарчук".into(),
            first_name: "Дмитро".into(),
            patronymic: "Олександрович".into(),
            address: "м. Вінниця, вул. Соборна, 20".into(),
            phone: "+380671235544".into(),
            grades: vec![5, 6, 5, 6],
        },
    ]
}
